INSERT INTO industries (slug, name) VALUES
('chemicals', 'Chemicals'),
('consulting', 'Consulting'),
('electrical', 'Electrical'),
('metal-works', 'Metal Works'),
('plastics', 'Plastics'),
('real-estate', 'Real Estate'),
('pharmaceuticals', 'Pharmaceuticals'),
('beauty-and-cosmetics', 'Beauty and Cosmetics'),
('events-management', 'Events Management'),
('wedding-and-accessories', 'Wedding and Accessories'),
('fuel-technology', 'Fuel Technology'),
('media', 'Media'),
('cements', 'Cements'),
('air-conditioning', 'Air Conditioning'),
('brick-manufacturing', 'Brick Manufacturing'),
('concrete-products', 'Concrete Products'),
('car-hiring', 'Car Hiring'),
('fireplaces', 'FirePlaces'),
('security', 'Security'),
('food-and-nutrition', 'Food and Nutrition'),
('stationery', 'Stationery'),
('health-and-hygiene', 'Health and Hygiene'),
('hardware', 'Hardware'),
('printing', 'Printing'),
('fashion', 'Fashion')
ON DUPLICATE KEY UPDATE name=VALUES(name);
